panda:
  torque_bias:
    - 0.0 # joint 1
    - 0.0 # joint 2
    - 0.0 # joint 3
    - 0.0 # joint 4
    - 0.0 # joint 5
    - 0.0 # joint 6
    - 0.0 # joint 7
  torque_stiction:
    - 0.45 # joint 1
    - 0.6 # joint 2
    - 0.4 # joint 3
    - 0.43 # joint 4
    - 0.25 # joint 5
    - 0.20 # joint 6
    - 0.2 # joint 7
